TYPE=VIEW
query=select `gp1`.`students`.`student_id` AS `userid`,`gp1`.`students`.`password` AS `userpass`,`gp1`.`students`.`student_name` AS `username`,1 AS `role`,`gp1`.`departments`.`dept_name` AS `userdept`,`gp1`.`colleges`.`col_name` AS `usercol`,`gp1`.`students`.`student_name` AS `personname`,`gp1`.`degrees`.`deg_id` AS `deg_id`,`gp1`.`degrees`.`deg_name` AS `deg_name` from (((`gp1`.`students` join `gp1`.`departments`) join `gp1`.`colleges`) join `gp1`.`degrees`) where `gp1`.`students`.`st_dept` = `gp1`.`departments`.`dept_id` and `gp1`.`departments`.`dept_col` = `gp1`.`colleges`.`col_id` and `gp1`.`students`.`st_deg` = `gp1`.`degrees`.`deg_id` union select concat(\'inst\',`gp1`.`instructors`.`inst_id`) AS `userid`,`gp1`.`instructors`.`inst_password` AS `userpass`,`gp1`.`instructors`.`inst_name` AS `username`,2 AS `role`,`gp1`.`departments`.`dept_name` AS `userdept`,`gp1`.`colleges`.`col_name` AS `usercol`,`gp1`.`instructors`.`inst_name` AS `personname`,NULL AS `deg_id`,NULL AS `deg_name` from ((`gp1`.`instructors` join `gp1`.`departments`) join `gp1`.`colleges`) where `gp1`.`instructors`.`inst_dept` = `gp1`.`departments`.`dept_id` and `gp1`.`departments`.`dept_col` = `gp1`.`colleges`.`col_id` union select concat(\'dept\',`gp1`.`departments`.`dept_id`) AS `userid`,`gp1`.`departments`.`dept_password` AS `userpass`,concat(\'رئيس \',`gp1`.`departments`.`dept_name`) AS `username`,3 AS `role`,`gp1`.`departments`.`dept_name` AS `userdept`,`gp1`.`colleges`.`col_name` AS `usercol`,`gp1`.`instructors`.`inst_name` AS `personname`,NULL AS `deg_id`,NULL AS `deg_name` from ((`gp1`.`departments` join `gp1`.`instructors`) join `gp1`.`colleges`) where `gp1`.`departments`.`dept_col` = `gp1`.`colleges`.`col_id` and `gp1`.`departments`.`dept_head` = `gp1`.`instructors`.`inst_id` union select concat(\'col\',`gp1`.`colleges`.`col_id`) AS `userid`,`gp1`.`colleges`.`col_password` AS `userpass`,concat(\'عميد \',`gp1`.`colleges`.`col_name`) AS `username`,4 AS `role`,NULL AS `userdept`,`gp1`.`colleges`.`col_name` AS `usercol`,`gp1`.`instructors`.`inst_name` AS `personname`,NULL AS `deg_id`,NULL AS `deg_name` from (`gp1`.`colleges` join `gp1`.`instructors`) where `gp1`.`colleges`.`col_dean` = `gp1`.`instructors`.`inst_id`
md5=4e761657f9d6e21314f2b65ec7e68cd8
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=0001713629716783986
create-version=2
source=select `students`.`student_id` AS `userid`,`students`.`password` AS `userpass`,`students`.`student_name` AS `username`,1 AS `role`,`departments`.`dept_name` AS `userdept`,`colleges`.`col_name` AS `usercol`,`students`.`student_name` AS `personname`,`degrees`.`deg_id` AS `deg_id`,`degrees`.`deg_name` AS `deg_name` from (((`students` join `departments`) join `colleges`) join `degrees`) where `students`.`st_dept` = `departments`.`dept_id` and `departments`.`dept_col` = `colleges`.`col_id` and `students`.`st_deg` = `degrees`.`deg_id` union select concat(\'inst\',`instructors`.`inst_id`) AS `userid`,`instructors`.`inst_password` AS `userpass`,`instructors`.`inst_name` AS `username`,2 AS `role`,`departments`.`dept_name` AS `userdept`,`colleges`.`col_name` AS `usercol`,`instructors`.`inst_name` AS `personname`,NULL AS `deg_id`,NULL AS `deg_name` from ((`instructors` join `departments`) join `colleges`) where `instructors`.`inst_dept` = `departments`.`dept_id` and `departments`.`dept_col` = `colleges`.`col_id` union select concat(\'dept\',`departments`.`dept_id`) AS `userid`,`departments`.`dept_password` AS `userpass`,concat(\'رئيس \',`departments`.`dept_name`) AS `username`,3 AS `role`,`departments`.`dept_name` AS `userdept`,`colleges`.`col_name` AS `usercol`,`instructors`.`inst_name` AS `personname`,NULL AS `deg_id`,NULL AS `deg_name` from ((`departments` join `instructors`) join `colleges`) where `departments`.`dept_col` = `colleges`.`col_id` and `departments`.`dept_head` = `instructors`.`inst_id` union select concat(\'col\',`colleges`.`col_id`) AS `userid`,`colleges`.`col_password` AS `userpass`,concat(\'عميد \',`colleges`.`col_name`) AS `username`,4 AS `role`,NULL AS `userdept`,`colleges`.`col_name` AS `usercol`,`instructors`.`inst_name` AS `personname`,NULL AS `deg_id`,NULL AS `deg_name` from (`colleges` join `instructors`) where `colleges`.`col_dean` = `instructors`.`inst_id`
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `gp1`.`students`.`student_id` AS `userid`,`gp1`.`students`.`password` AS `userpass`,`gp1`.`students`.`student_name` AS `username`,1 AS `role`,`gp1`.`departments`.`dept_name` AS `userdept`,`gp1`.`colleges`.`col_name` AS `usercol`,`gp1`.`students`.`student_name` AS `personname`,`gp1`.`degrees`.`deg_id` AS `deg_id`,`gp1`.`degrees`.`deg_name` AS `deg_name` from (((`gp1`.`students` join `gp1`.`departments`) join `gp1`.`colleges`) join `gp1`.`degrees`) where `gp1`.`students`.`st_dept` = `gp1`.`departments`.`dept_id` and `gp1`.`departments`.`dept_col` = `gp1`.`colleges`.`col_id` and `gp1`.`students`.`st_deg` = `gp1`.`degrees`.`deg_id` union select concat(\'inst\',`gp1`.`instructors`.`inst_id`) AS `userid`,`gp1`.`instructors`.`inst_password` AS `userpass`,`gp1`.`instructors`.`inst_name` AS `username`,2 AS `role`,`gp1`.`departments`.`dept_name` AS `userdept`,`gp1`.`colleges`.`col_name` AS `usercol`,`gp1`.`instructors`.`inst_name` AS `personname`,NULL AS `deg_id`,NULL AS `deg_name` from ((`gp1`.`instructors` join `gp1`.`departments`) join `gp1`.`colleges`) where `gp1`.`instructors`.`inst_dept` = `gp1`.`departments`.`dept_id` and `gp1`.`departments`.`dept_col` = `gp1`.`colleges`.`col_id` union select concat(\'dept\',`gp1`.`departments`.`dept_id`) AS `userid`,`gp1`.`departments`.`dept_password` AS `userpass`,concat(\'رئيس \',`gp1`.`departments`.`dept_name`) AS `username`,3 AS `role`,`gp1`.`departments`.`dept_name` AS `userdept`,`gp1`.`colleges`.`col_name` AS `usercol`,`gp1`.`instructors`.`inst_name` AS `personname`,NULL AS `deg_id`,NULL AS `deg_name` from ((`gp1`.`departments` join `gp1`.`instructors`) join `gp1`.`colleges`) where `gp1`.`departments`.`dept_col` = `gp1`.`colleges`.`col_id` and `gp1`.`departments`.`dept_head` = `gp1`.`instructors`.`inst_id` union select concat(\'col\',`gp1`.`colleges`.`col_id`) AS `userid`,`gp1`.`colleges`.`col_password` AS `userpass`,concat(\'عميد \',`gp1`.`colleges`.`col_name`) AS `username`,4 AS `role`,NULL AS `userdept`,`gp1`.`colleges`.`col_name` AS `usercol`,`gp1`.`instructors`.`inst_name` AS `personname`,NULL AS `deg_id`,NULL AS `deg_name` from (`gp1`.`colleges` join `gp1`.`instructors`) where `gp1`.`colleges`.`col_dean` = `gp1`.`instructors`.`inst_id`
mariadb-version=100432
